---
latitude: 59.68631
longitude: 18.78079
map_zoom: 12
name: Marholmen
email: bokning@marholmen.se
phone_number: 0771-16 17 00
address:
  street1: Marholmen 1
  street2: ''
  state: ''
  city: Norrtalje
  country: 
  zip_code: '76197'
_hotel_id: MAR889
_portal_id: marholmen
default_currency: SEK
footer_logo: Marholmen is an island in Roslagens sk&auml;rg&aring;rd only one hour's
  drive from Stockholm. This nature's oasis is ideal for conferences, parties and
  relaxing meetings.
logo: <img id="1515670677710" class=" " src="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/LOGO-SMALL.jpg"
  data-image-large="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/large_LOGO_SMALL.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/medium_LOGO_SMALL.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/small_LOGO_SMALL.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/xsmall_LOGO_SMALL.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-11-063756/thumb_LOGO_SMALL.jpg"
  />
footer_last_column: <img id="1517326749259" class=" " src="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/de-Luxe-room-detail.jpg"
  width="180" height="271" data-image-large="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/large_de_Luxe_room_detail.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/medium_de_Luxe_room_detail.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/small_de_Luxe_room_detail.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/xsmall_de_Luxe_room_detail.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103902/thumb_de_Luxe_room_detail.jpg"
  />&nbsp;<img id="1517326788928" class=" " src="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/Spa-bubbel-tavelv-gg.jpg"
  width="185" height="268" data-image-large="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/large_Spa_bubbel_tavelv%C3%A4gg.jpg"
  data-image-medium="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/medium_Spa_bubbel_tavelv%C3%A4gg.jpg"
  data-image-small="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/small_Spa_bubbel_tavelv%C3%A4gg.jpg"
  data-image-xsmall="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/xsmall_Spa_bubbel_tavelv%C3%A4gg.jpg"
  data-image-thumb="//cdn.traveltripper.io/site-assets/32_846_10951/media/2018-01-30-103946/thumb_Spa_bubbel_tavelv%C3%A4gg.jpg"
  />
