---
latitude: 59.68631
longitude: 18.78079
map_zoom: 12
name: Marholmen
email: victor@traveltripper.com
phone_number: 0771-16 17 00
address:
  street1: Marholmen 1
  street2: ''
  state: ''
  city: Norrtalje
  country: 
  zip_code: '76197'
_hotel_id: MAR889
_portal_id: required-but-empty
footer_logo: Marholmen is an island in Roslagens sk&auml;rg&aring;rd only one hour's
  drive from Stockholm. This nature's oasis is ideal for conferences, parties and
  relaxing meetings.
